import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';
import { compileMessage } from '@lingui/message-utils/compileMessage';

// couponText uses an explicit t(message, values) wrapper rather than Lingui
// macros. Extract its literal descriptors from syntax, including escaped text.
export function extractCouponDescriptors(code, filename = 'coupons-blocks.ts') {
  const source = ts.createSourceFile(filename, code, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  if (source.parseDiagnostics.length) throw new Error('Coupon translation source does not parse');
  const messages = new Set();
  const visit = node => {
    if (ts.isCallExpression(node) && ts.isIdentifier(node.expression) && node.expression.text === 't') {
      const message = node.arguments[0];
      if (!message || !(ts.isStringLiteral(message) || ts.isNoSubstitutionTemplateLiteral(message))) {
        throw new Error('Unsupported dynamic coupon translation descriptor');
      }
      messages.add(message.text);
    }
    ts.forEachChild(node, visit);
  };
  visit(source);
  if (!messages.size) throw new Error('Coupon translation catalog is empty');
  return [...messages].sort();
}

export function renderCouponCatalog(code) {
  const messages = Object.fromEntries(extractCouponDescriptors(code).map(message => [message, compileMessage(message)]));
  return '// Generated by scripts/coupon-catalog.mjs using @lingui/message-utils 5.9.5.\n' +
    '// English fallback only; unsupported host locales retain their direction.\n' +
    'export const englishCouponCatalog = ' + JSON.stringify(messages, null, 2) + ' as const;\n';
}

export async function checkCouponCatalog(root, { write = false } = {}) {
  const compiler = JSON.parse(await readFile(resolve(root, 'node_modules/@lingui/message-utils/package.json'), 'utf8'));
  if (compiler.version !== '5.9.5') throw new Error('Pinned Lingui catalog compiler changed');
  const source = await readFile(resolve(root, 'src/admin/coupons-blocks.ts'), 'utf8');
  const generated = renderCouponCatalog(source);
  const target = resolve(root, 'src/admin/coupon-catalog.ts');
  if (write) await writeFile(target, generated);
  else if (await readFile(target, 'utf8') !== generated) {
    throw new Error('Coupon catalog is missing or stale; run node scripts/coupon-catalog.mjs --write');
  }
  return extractCouponDescriptors(source).length;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  console.log(`Checked ${await checkCouponCatalog(resolve('.'), { write: process.argv.includes('--write') })} coupon messages`);
}
