// Generated by scripts/coupon-catalog.mjs using @lingui/message-utils 5.9.5.
// English fallback only; unsupported host locales retain their direction.
export const englishCouponCatalog = {
  "Active": [
    "Active"
  ],
  "Code": [
    "Code"
  ],
  "Consumed redemptions": [
    "Consumed redemptions"
  ],
  "Could not complete the request. Reload and try again.": [
    "Could not complete the request. Reload and try again."
  ],
  "Coupon changes were not saved. {reason}": [
    "Coupon changes were not saved. ",
    [
      "reason"
    ]
  ],
  "Coupon created": [
    "Coupon created"
  ],
  "Coupon disabled": [
    "Coupon disabled"
  ],
  "Coupon saved": [
    "Coupon saved"
  ],
  "Coupons": [
    "Coupons"
  ],
  "Coupons are unavailable. Reload and try again.": [
    "Coupons are unavailable. Reload and try again."
  ],
  "Coupons require plugins:manage": [
    "Coupons require plugins:manage"
  ],
  "Create coupon": [
    "Create coupon"
  ],
  "Create your first coupon below.": [
    "Create your first coupon below."
  ],
  "Dates require an explicit offset. End is exclusive. Percentage values are 0–100; fixed values are USD.": [
    "Dates require an explicit offset. End is exclusive. Percentage values are 0–100; fixed values are USD."
  ],
  "Disable": [
    "Disable"
  ],
  "Disable coupon": [
    "Disable coupon"
  ],
  "Disable coupon?": [
    "Disable coupon?"
  ],
  "Disabled": [
    "Disabled"
  ],
  "Discount": [
    "Discount"
  ],
  "Discount value": [
    "Discount value"
  ],
  "Edit coupon": [
    "Edit coupon"
  ],
  "Ends at (ISO offset, exclusive)": [
    "Ends at (ISO offset, exclusive)"
  ],
  "Expired": [
    "Expired"
  ],
  "Fixed amount (USD)": [
    "Fixed amount (USD)"
  ],
  "Keep enabled": [
    "Keep enabled"
  ],
  "Merchant timezone (IANA)": [
    "Merchant timezone (IANA)"
  ],
  "New coupon": [
    "New coupon"
  ],
  "New redemptions will be refused.": [
    "New redemptions will be refused."
  ],
  "Next": [
    "Next"
  ],
  "No coupons yet": [
    "No coupons yet"
  ],
  "Open {code}": [
    "Open ",
    [
      "code"
    ]
  ],
  "Pending holds": [
    "Pending holds"
  ],
  "Percentage": [
    "Percentage"
  ],
  "Previous": [
    "Previous"
  ],
  "Products": [
    "Products"
  ],
  "Released attempts": [
    "Released attempts"
  ],
  "Remaining capacity": [
    "Remaining capacity"
  ],
  "Save coupon": [
    "Save coupon"
  ],
  "Settings": [
    "Settings"
  ],
  "Starts at (ISO offset)": [
    "Starts at (ISO offset)"
  ],
  "This coupon changed. Reopen it to review current values before saving.": [
    "This coupon changed. Reopen it to review current values before saving."
  ],
  "Upcoming": [
    "Upcoming"
  ],
  "Usage limit": [
    "Usage limit"
  ],
  "{code} — {state} — {consumed} consumed / {remaining} remaining": [
    [
      "code"
    ],
    " — ",
    [
      "state"
    ],
    " — ",
    [
      "consumed"
    ],
    " consumed / ",
    [
      "remaining"
    ],
    " remaining"
  ]
} as const;
