// Generated by scripts/coupon-catalog.mjs using @lingui/message-utils 5.9.5.
// English fallback only; unsupported host locales retain their direction.
// Store plain descriptors once; retain the compiler output for interpolation.
const plain = [
  "Active",
  "Code",
  "Consumed redemptions",
  "Coupon created",
  "Coupon disabled",
  "Coupon saved",
  "Coupons",
  "Coupons require plugins:manage",
  "Coupons unavailable. Reload.",
  "Create coupon",
  "Disable",
  "Disable coupon",
  "Disable coupon?",
  "Disabled",
  "Discount",
  "Discount value",
  "Edit coupon",
  "Ends at (ISO offset, exclusive)",
  "Expired",
  "Fixed amount (USD)",
  "Keep enabled",
  "Merchant timezone (IANA)",
  "New coupon",
  "New redemptions stop.",
  "Next",
  "No coupons yet",
  "None yet.",
  "Offset required. End exclusive.",
  "Pending holds",
  "Percentage",
  "Previous",
  "Products",
  "Released attempts",
  "Reload and try again.",
  "Remaining capacity",
  "Save coupon",
  "Settings",
  "Starts at (ISO offset)",
  "This coupon changed. Reopen it.",
  "Upcoming",
  "Usage limit"
] as const;
export const englishCouponCatalog = { ...Object.fromEntries(plain.map(message => [message, [message]])),
...Object.fromEntries([
  [
    "Coupon changes were not saved. ",
    [
      "reason"
    ]
  ],
  [
    "Open ",
    [
      "code"
    ]
  ],
  [
    [
      "code"
    ],
    " — ",
    [
      "state"
    ],
    " — ",
    [
      "consumed"
    ],
    " consumed / ",
    [
      "remaining"
    ],
    " remaining"
  ]
].map(parts => [parts.map(part => typeof part === "string" ? part : "{" + part[0] + "}").join(""), parts])) } as const;
