// Generated by scripts/coupon-catalog.mjs using @lingui/message-utils 5.9.5.
// English fallback only; unsupported host locales retain their direction.
// Store plain descriptors once; retain the compiler output for interpolation.
const plain = [
  "Active",
  "Code",
  "Consumed redemptions",
  "Could not complete the request. Reload and try again.",
  "Coupon created",
  "Coupon disabled",
  "Coupon saved",
  "Coupons",
  "Coupons are unavailable. Reload and try again.",
  "Coupons require plugins:manage",
  "Create coupon",
  "Create your first coupon below.",
  "Dates require an explicit offset. End is exclusive. Percentage values are 0–100; fixed values are USD.",
  "Disable",
  "Disable coupon",
  "Disable coupon?",
  "Disabled",
  "Discount",
  "Discount value",
  "Edit coupon",
  "Ends at (ISO offset, exclusive)",
  "Expired",
  "Fixed amount (USD)",
  "Keep enabled",
  "Merchant timezone (IANA)",
  "New coupon",
  "New redemptions will be refused.",
  "Next",
  "No coupons yet",
  "Pending holds",
  "Percentage",
  "Previous",
  "Products",
  "Released attempts",
  "Remaining capacity",
  "Save coupon",
  "Settings",
  "Starts at (ISO offset)",
  "This coupon changed. Reopen it to review current values before saving.",
  "Upcoming",
  "Usage limit"
] as const;
export const englishCouponCatalog = { ...Object.fromEntries(plain.map(message => [message, [message]])),
...Object.fromEntries([
  [
    "Coupon changes were not saved. ",
    [
      "reason"
    ]
  ],
  [
    "Open ",
    [
      "code"
    ]
  ],
  [
    [
      "code"
    ],
    " — ",
    [
      "state"
    ],
    " — ",
    [
      "consumed"
    ],
    " consumed / ",
    [
      "remaining"
    ],
    " remaining"
  ]
].map(parts => [parts.map(part => typeof part === "string" ? part : "{" + part[0] + "}").join(""), parts])) } as const;
